mysql:
  path: 192.168.123.51
  port: 4316
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: sv_auth
  username: root
  password: root
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
redis:
  db: 0
  addr: 192.168.123.51:7389
  password: ""
system:
  id: 1518512539921547264
  env: public
  addr: :7698
  rpc-addr: :51078
  sso-rpc-addr: 192.168.123.51:51098
  db-type: mysql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
zap:
  level: info
  format: console
  prefix: '[github.com/svcodestore/sv-auth-gin]'
  director: logs
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
jwt:
  buffer-time: 86400
  expires-time: 604800
  issuer: http://192.168.123.51:7698
  signing-key: 