FROM golang:1.17 AS API
WORKDIR /sv-auth-gin
COPY ./sv-auth-gin/ .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o http_server ./main.go && mkdir run && mv ./http_server ./config.yaml run
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o rpc_server ./rpc.go && mv ./rpc_server run

FROM alpine:latest
RUN echo "mysql:
  path: 192.168.123.51
  port: 4316
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: sv_auth
  username: root
  password: root
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
redis:
  db: 0
  addr: 192.168.123.51:7389
  password: ""
system:
  id: 1518512539921547264
  env: public
  addr: :7698
  rpc-addr: :51078
  sso-rpc-addr: 192.168.123.51:51098
  db-type: mysql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
zap:
  level: info
  format: console
  prefix: '[github.com/svcodestore/sv-auth-gin]'
  director: logs
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
jwt:
  buffer-time: 86400
  expires-time: 604800
  issuer: http://192.168.123.51:7698
  signing-key: " > ./config.yaml

CMD ["sh", "-c", "./http_server & \n ./rpc_server"]